name: pranag_flutter_ui
description: PRANA-G UI port in Flutter (offline AI workflow)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.5.3
  firebase_core: ^2.30.1
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.2
  connectivity_plus: ^6.0.5
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.5.4
  record: ^6.1.1
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/home.png
    - assets/models/
